"""Constants used throughout the bot."""

SORCERY_NICKNAMES = [
    "Grapple Goof",
    "Blink Bandit",
    "Infiltrator Iguana",
    "Poisonous Platypus",
    "Disenchant Dingo",
    "Lightning Llama",
    "Common Silliness",
    "Blazing Baboon",
    "Minor Explosion Mouse",
    "Firebolt Ferret",
    "Buried Banana",
    "Dispel Duck",
    "Disintegrate Donkey",
    "Devil's Pact Penguin",
    "Plague Frog",
    "Earthquake Emu",
    "Riptide Rhino",
    "Magic Missile Marmot",
    "Shatter Sheep",
    "Browsing Beaver",
    "Polymorph Pony",
    "Mesmerized Mole",
    "Critical Cat",
    "Heat Ray Hamster",
    "Warped Walrus",
    "Drowning Duckling",
    "Major Explosion Moose",
    "Crow Feast",
    "Whirling Weasel",
    "Craterized Crab",
    "Mad Dash Dachshund",
    "Spinny Spider",
    "Geyser Goat",
    "Arcane Barrage Antelope",
    "Dream-Quest Duck",
    "Flanking Ferret",
    "Teleporting Tortoise",
    "Divine Hamster",
    "Gigantic Giraffe",
    "Leaping Lemur",
    "Dodgy Dog",
    "Extinguished Elephant",
    "Shrunken Sheep",
    "Exiled Eel",
    "Lava Lizard",
    "Astray Alpaca",
    "Shapeshifting Shrew",
    "Snowball Seal",
    "Tactical Tapir",
    "Chain Lightning Chicken",
    "Psionic Pig",
    "Windblasted Wombat",
    "Assorted Armadillo",
    "Boiling Bat",
    "Flame Wave Fox",
    "Immolated Ibex",
    "Marine Mink",
    "Replicating Raccoon",
    "Sleepy Sloth",
    "Arc Lightning Lynx",
    "Night Attack Newt",
    "Ball Lightning Badger",
    "Charging Chinchilla",
    "Firebreathing Ferret",
    "Insulted Ibis",
    "King's Kangaroo",
    "Peasant Penguin",
    "Pendragon Pug",
    "Valiant Vole",
    "Vanishing Viper",
    "Twisted Tiger",
    "Fading Finch",
    "Occult Otter",
    "Rainy Raccoon",
    "Dead-raising Duck",
    "Recall Rabbit",
    "Telekinetic Toad",
    "Unlikely Unicorn",
    "Waypoint Wombat",
    "Cave-In Capybara",
    "Exorcist Egret",
    "Minecart Mole",
    "Overpowering Owl",
    "Shield Sheep",
    "Star-seed Squirrel",
    "Unraveling Urchin",
    "Backstabbing Beaver",
    "Cone of Cat",
    "Fireball Fox",
    "Incinerated Ibex",
    "Meteor Mouse",
    "Scorched Salamander",
    "Harpooning Hamster",
    "Font of Ferret",
    "Frosty Fox",
    "Icy Iguana",
    "Stormy Stoat",
    "Twisted Tapir",
    "Upwelling Urchin",
    "Wrathful Walrus",
    "Burning Badger",
    "Degraded Duck",
    "Dueling Dog",
    "Guarding Goose",
    "Jousting Jackal",
    "Knightly Koala",
    "Flying Ferret",
    "Rescue Rat",
    "Stone Rain Squirrel",
    "Whirlwind Weasel",
]
