name: Deploy Web App

on:
  push:
    branches:
      - main
    paths:
      - "web-app/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Linode
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.LINODE_HOST }}
          username: ${{ secrets.LINODE_USER }}
          key: ${{ secrets.LINODE_SSH_KEY }}
          script: |
            cd /root/Summit/SummitDiscordBot
            git pull origin main
            cd web-app
            pip install -r requirements.txt
            systemctl restart summit-web
